### ISSUE TITLE
Require last call to have discussion end date

### ISSUE THREAD

**Issue by fulldecent** [eip-automerger/automerger#1]
Here is one example

https://github.com/ethereum/EIPs/pull/1427

Last calls should have a `review-period-end` set.

**Comment by axic** [comment]
Maybe this should be implemented in the [eip_validator](https://rubygems.org/gems/eip_validator).

**Comment by axic** [comment]
@fulldecent reported it here: https://github.com/makoto/eip_validator/issues/6

Can you close this?

**Comment by fulldecent** [comment]
Yes, thank you.
